# Generated by Django 2.2 on 2020-03-27 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='abc', max_length=500),
            preserve_default=False,
        ),
    ]
