# Generated by Django 2.2 on 2020-02-02 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='vote_type',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
