# Generated by Django 2.2 on 2020-03-31 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200331_2230'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('username', 'email')},
        ),
        migrations.CreateModel(
            name='SocialMediaDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_name', models.CharField(max_length=20)),
                ('user_email', models.EmailField(max_length=254)),
                ('social_user_id', models.CharField(max_length=500)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.User')),
            ],
            options={
                'unique_together': {('platform_name', 'user_email')},
            },
        ),
    ]
