# Generated by Django 2.2 on 2020-04-07 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20200401_0353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmediadetails',
            name='user_email',
            field=models.EmailField(default=None, max_length=254, null=True),
        ),
    ]
