# Generated by Django 2.2 on 2020-04-21 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_idea_user_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='idea',
            options={'ordering': ['-votes', '-date_time']},
        ),
    ]
