# Generated by Django 2.2 on 2020-04-26 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20200421_2114'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-date_time']},
        ),
        migrations.AddField(
            model_name='idea',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
