# Generated by Django 2.2 on 2020-09-04 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_userfcmdevice'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='idea',
            name='repo_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
