# Generated by Django 2.2 on 2020-03-28 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='evaluated',
            field=models.BooleanField(default=False),
        ),
    ]
