# Generated by Django 2.2 on 2020-04-07 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0004_auto_20200402_0006'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-date_time']},
        ),
    ]
