# Generated by Django 2.2 on 2020-02-02 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_vote_vote_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='email',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='phone_no',
        ),
    ]
