# Generated by Django 2.2 on 2020-02-03 12:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200203_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='reviewer_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_id_idea', to=settings.AUTH_USER_MODEL),
        ),
    ]
