# Generated by Django 2.2 on 2020-02-04 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, default='2020-02-01T11:53:56.808223Z'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vote',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, default='2020-02-01T11:53:56.808223Z'),
            preserve_default=False,
        ),
    ]
